### ISSUE TITLE
NODE_MODULE_VERSION 72

### ISSUE THREAD

**Issue by nicolaric** [meg768/rpi-ws281x#3]
Hi,
Unfortunatly I can't use this module with NODE_MODULE_VERSION 72 nodejs version Node.js 12.16.2.
Following Error is thrown:

```
Error: The module '/home/pi/projects/light/node_modules/rpi-ws281x-v2/build/Release/rpi-ws281x.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 72. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1206:18)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/home/pi/projects/light/node_modules/rpi-ws281x-v2/index.js:7:13)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
free(): invalid pointer
```

**Comment by SimonGAndrews** [comment]
Hi , does this help.  https://stackoverflow.com/questions/46384591/node-was-compiled-against-a-different-node-js-version-using-node-module-versio://stackoverflow.com/questions/46384591/node-was-compiled-against-a-different-node-js-version-using-node-module-versio

**Comment by SimonGAndrews** [comment]
https://stackoverflow.com/questions/46384591/node-was-compiled-against-a-different-node-js-version-using-node-module-versio

Does this help ??  Looks similar

**Comment by meg768** [comment]
https://github.com/meg768/rpi-ws281x/issues/6
